// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ngHdz1ZKZDPWwGxjvv3O2NUTyawPJIw',
    appId: '1:153884778588:web:7133a00b893a94443e8699',
    messagingSenderId: '153884778588',
    projectId: 'study-app-558c7',
    authDomain: 'study-app-558c7.firebaseapp.com',
    storageBucket: 'study-app-558c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8fx-iqRYhnZJyLShSwmBGuaMrIVFTOR4',
    appId: '1:153884778588:android:29503338c32051d03e8699',
    messagingSenderId: '153884778588',
    projectId: 'study-app-558c7',
    storageBucket: 'study-app-558c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnkJLSykrM1mSUD7sbSMPzsx1jQJh0uUw',
    appId: '1:153884778588:ios:395628497b139d5a3e8699',
    messagingSenderId: '153884778588',
    projectId: 'study-app-558c7',
    storageBucket: 'study-app-558c7.appspot.com',
    iosClientId: '153884778588-u92b6cp2jdm7tmn2cdl80ilh2rh92t37.apps.googleusercontent.com',
    iosBundleId: 'com.abhishek.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnkJLSykrM1mSUD7sbSMPzsx1jQJh0uUw',
    appId: '1:153884778588:ios:395628497b139d5a3e8699',
    messagingSenderId: '153884778588',
    projectId: 'study-app-558c7',
    storageBucket: 'study-app-558c7.appspot.com',
    iosClientId: '153884778588-u92b6cp2jdm7tmn2cdl80ilh2rh92t37.apps.googleusercontent.com',
    iosBundleId: 'com.abhishek.flutterStudyApp',
  );
}
